#07-Jun-2016 - Control string for \MAGNETICS::TOP.SHOELACE:FREQ_PROGRAM:FREQ_WAVE_HZ Shoelace antenna - autogenerated from genPythonStampFun.m

from MDSplus import *
from numpy import array

tree=Tree("magnetics",-1)
expr=Data.compile("Build_Signal([70000.00000, 70000.00000, 70000.00000, 112000.00000, 112000.00000, 70000.00000, 70000.00000, 112000.00000, 112000.00000, 70000.00000, 70000.00000], *, [-0.10000, 0.77425, 0.79900, 0.87450, 0.89925, 0.97475, 0.99950, 1.07500, 1.09975, 1.17525, 4.00000]+-0.05000)")
tree.getNode("\MAGNETICS::TOP.SHOELACE:FREQ_PROGRAM:FREQ_WAVE_HZ").putData(expr)
