#07-Jun-2016 - Control string for \MAGNETICS::TOP.SHOELACE:AMP_PROGRAM:AMP_WAVE_W Shoelace antenna - autogenerated from genPythonStampFun.m

from MDSplus import *
from numpy import array

tree=Tree("magnetics",-1)
expr=Data.compile("_tOn=\MAGNETICS::TOP.SHOELACE:RF_GATE:ON, _tOff=\MAGNETICS::TOP.SHOELACE:RF_GATE:OFF, _tRise=\MAGNETICS::TOP.SHOELACE:AMP_PROGRAM:T_RISE, _tFall=\MAGNETICS::TOP.SHOELACE:AMP_PROGRAM:T_FALL, Build_Signal(2500.0 * [0.0, 0.0, 1.0, 1.0, 0.0, 0.0,  0.0], *, _tOn+[-0.10000-_tOn,  0.00000, 0.05000, 0.49999, 0.54999, 0.54999,  3.30000])")
tree.getNode("\MAGNETICS::TOP.SHOELACE:AMP_PROGRAM:AMP_WAVE_W").putData(expr)
